// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestApp.Masterdb.EF.Models
{
    public partial class Supervisor
    {
        public int SupervisorID { get; set; }
        public int? WorkerID { get; set; }
        public decimal? AnnualSalary { get; set; }

        public virtual Worker Worker { get; set; }
    }
}