// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestApp.Masterdb.EF.Models
{
    public partial class Worker
    {
        public Worker()
        {
            Employees = new HashSet<Employee>();
            Managers = new HashSet<Manager>();
            Supervisors = new HashSet<Supervisor>();
        }

        public int WorkerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Manager> Managers { get; set; }
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}